config/routes.rb
Rails.application.routes.draw do
  devise_scope :user {
    get '/signin' => 'devise/sessions#new'
    get '/signup' => 'devise/registrations#new'
    get '/'       => 'users#show'
   }

  devise_for :users
  root to: "home#index"

  resources :users, only: [:index, :show]
  resources :boats
  resources :jobs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/add_boat_id_to_job.rb
class AddBoatIdToJob < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boat.rb
class Boat < ApplicationRecord
  has_many :jobs
  belongs_to :user
  validates :name, presence: true, uniqueness: true

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/home.rb
class Home < ApplicationRecord
  
end

app/models/job.rb
class Job < ApplicationRecord
  has_many :boats
  belongs_to :user
  validates :name, presence: true, uniqueness: true
  validates_numericality_of :cost, :only_integer => true, :greater_than_or_equal_to => 1000
  validates :description, length: { minimum: 50 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :boats
  has_many :jobs
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
  before_action :set_boat, only: [:show, :edit, :update, :destroy]

  def index
    @boats = current_user.boats.all
  end

  def show
  end

  def new
    @boat = Boat.new
  end

  def edit
  end

  def create
    @boat = current_user.boats.new(boat_params)

    respond_to do |format|
      if @boat.save
        format.html { redirect_to @boat, notice: 'Boat was successfully created.' }
        format.json { render :show, status: :created, location: @boat }
      else
        format.html { render :new }
        format.json { render json: @boat.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @boat.update(boat_params)
        format.html { redirect_to @boat, notice: 'Boat was successfully updated.' }
        format.json { render :show, status: :ok, location: @boat }
      else
        format.html { render :edit }
        format.json { render json: @boat.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @boat.destroy
    respond_to do |format|
      format.html { redirect_to boats_url, notice: 'Boat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_boat
      @boat = Boat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def boat_params
      params.require(:boat).permit(:user_id, :job_id, :name, :containers, :location, :image)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @boats = current_user.boats.all
  end


end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  def index
    @jobs = Job.all
  end

  def show
    @boats = current_user.boats
    @boat = Boat.find_by_id(params[:boat_id])
  end

  def new
    @job = Job.new
  end

  def edit
  end

  def create
    @job = current_user.jobs.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:user_id, :boat_id, :name, :description, :origin, :destination, :cost, :containers)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index

  end

  def show
    @boats = current_user.boats
    @jobs = current_user.jobs
    @boat = Boat.find_by_id(params[:boat_id])
  end

  private

  def user_params
    params.require(:user).permit(:boat_id, :job_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boats_helper.rb
module BoatsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boats/_form.html.erb
<%= form_with(model: @boat, local: true, html: { multipart: true }) do |form| %>
  <% if @boat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(boat.errors.count, "error") %> prohibited this boat from being saved:</h2>

      <ul>
      <% @boat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %> <br>
    <%= form.text_field :name, id: :boat_name %>
  </div>

  <div class="field">
    <%= form.label :containers %> <br>
    <%= form.number_field :containers, id: :boat_containers %>
  </div>

  <div class="field">
    <%= form.label :location %> <br>
    <%= form.select :location, ['California', 'Florida', 'Louisiana', 'Maryland', 'North Carolina', 'New Jersey', 'New York', 'Pennsylvania', 'South Carolina', 'Texas', 'Washington'] %>
  </div>

  <div class="image_field">
    <%= form.label :image %> <br>
    <%= form.file_field :image, :class => "image_button" %>
  </div>

  <div class="actions">
    <%= form.submit 'Create Boat', :class => 'submit_button' %>
  </div>
<% end %>

app/views/boats/edit.html.erb
<div id="page_wrapper">
  <h1>Edit Boat</h1>

  <%= render 'form', boat: @boat %>

  <%= link_to 'Show', @boat %> |
  <%= link_to 'Back', boats_path %>
</div>

app/views/boats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Boats</h1>

<table class="results">
  <thead>
    <tr>
      <th class="limit">Name</th>
      <th class="limit">Containers</th>
      <th class="limit">Location</th>
      <th class="limit" colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @boats.each do |boat| %>
      <tr>
        <td class="limit"><%= boat.name %></td>
        <td class="limit"><%= boat.containers %></td>
        <td class="limit"><%= boat.location %></td>
        <td class="limit"><%= link_to 'Show', boat %>
          <%= link_to 'Edit', edit_boat_path(boat) %>
          <%= link_to 'Destroy', boat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Boat', new_boat_path %>

app/views/boats/new.html.erb
<div class="boat_job_form">
  <h2>New Boat</h2>

  <%= render 'form', boat: @boat %>
</div>

app/views/boats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @boat.name %>
</p>
<br>

<p>
  <strong>Containers:</strong>
  <%= @boat.containers %>
</p>
<br>

<p>
  <strong>Location:</strong>
  <%= @boat.location %>
</p>
<br>

<p>
  <strong>Image:</strong>
  <%= image_tag @boat.image.url(:medium) %>
</p>
<br>

<div class="showBtn">
  <%= link_to 'Edit', edit_boat_path(@boat) %> |
  <%= link_to 'Back', boats_path %>
</div>

app/views/home/index.html.erb
<h1>Home</h1>

app/views/jobs/_form.html.erb
<%= form_with(model: @job, local: true) do |form| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %> <br>
    <%= form.text_field :name, id: :job_name %>
  </div>

  <div class="field">
    <%= form.label :description %> <br>
    <%= form.text_area :description, id: :job_description %>
  </div>

  <div class="field">
    <%= form.label :origin %> <br>
    <%= form.select :origin, ['California', 'Florida', 'Louisiana', 'Maryland', 'North Carolina', 'New Jersey', 'New York', 'Pennsylvania', 'South Carolina', 'Texas', 'Washington'] %>
  </div>

  <div class="field">
    <%= form.label :destination %> <br>
    <%= form.select :destination, ['California', 'Florida', 'Louisiana', 'Maryland', 'North Carolina', 'New Jersey', 'New York', 'Pennsylvania', 'South Carolina', 'Texas', 'Washington'] %>
  </div>

  <div class="field">
    <%= form.label :cost %> <br>
    <%= form.number_field :cost, id: :job_cost %>
  </div>

  <div class="field">
    <%= form.label :containers %> <br>
    <%= form.number_field :containers, id: :job_containers %>
  </div>

  <div class="actions">
    <%= form.submit 'Create Job', :class => 'submit_button'%>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<div id="page_wrapper">
  <h1>Edit Job</h1>

  <%= render 'form', job: @job %>

  <%= link_to 'Show', @job %> |
  <%= link_to 'Back', jobs_path %>
</div>

app/views/jobs/index.html.erb
<div class="jobTable">
  <p id="notice"><%= notice %></p>

  <h1>Jobs</h1>

  <table class="results">
    <thead>
      <tr>
        <th class="limit"><h2>Name</h2></th>
        <th class="limit"><h2>Description</h2></th>
        <th class="limit"><h2>Origin</h2></th>
        <th class="limit"><h2>Destination</h2></th>
        <th class="limit"><h2>Cost</h2></th>
        <th class="limit"><h2>Containers</h2></th>
        <th class="limit" colspan="7"><h2>Links</h2></th>
      </tr>
    </thead>

    <tbody>
      <% @jobs.each do |job| %>
        <tr>
          <td class="limit"><%= job.name %></td>
          <td class="limit"><%= job.description %></td>
          <td class="limit"><%= job.origin %></td>
          <td class="limit"><%= job.destination %></td>
          <td class="limit"><%= job.cost %></td>
          <td class="limit"><%= job.containers %></td>
          <td class="limit"><%= link_to 'Show', job %>
              <%= link_to 'Edit', edit_job_path(job) %>
              <%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
  <%= link_to 'New Job', new_job_path %>
</div>

app/views/jobs/new.html.erb
<div class="boat_job_form">
  <h2>New Job</h2>

  <%= render 'form', job: @job %>
</div>

app/views/jobs/show.html.erb
<h1>View Job</h1>
<p id="notice"><%= notice %></p>
<p><strong>Name:</strong> <%= @job.name %></p>

<p><strong>Description:</strong> <%= @job.description %></p>

<p><strong>Origin:</strong> <%= @job.origin %></p>

<p><strong>Destination:</strong> <%= @job.destination %></p>

<p><strong>Cost:</strong> <%= @job.cost %></p>

<p><strong>Containers:</strong> <%= @job.containers %></p>

<p><strong>Job Status:</strong><span id="status"> <%= @job.boat_id %></span></p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

<br><br>
<h2>Add a Boat</h2>
<% @boats.each do |boat| %>
  <p><strong>Name:</strong> <%= boat.name %></p>
  <p><strong>Containers:</strong> <%= boat.containers %></p>
  <p><strong>Location:</strong> <%= boat.location %></p>
  <p><strong>Image:</strong><%= image_tag boat.image.url(:medium) %></p>

  <%= form_for @job do |f| %>
    <%= f.hidden_field :boat_id, value: boat.id %>

    <span><%= button_to 'Add to Job', @job, method: :put, remote: true, id: "addBtn", data: { confirm: 'Are you sure?' } %></span>
  <% end %>

  <hr>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Boat Project</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="topnav">
      <ul>
        <% if current_user %>
        <li><%= link_to "Dashboard", root_path %></li>
        <li><%= link_to "Jobs", jobs_path %></li>
        <li><%= link_to "New Boat", new_boat_path %></li>
        <li><%= link_to "New Job", new_job_path %></li>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "Sign In", new_user_session_path %></li>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
    <div><p class="alert"><%= alert %></p></div>
    <br>
    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>

</html>

app/views/users/index.html.erb
<h1>Index</h1>

app/views/users/new.html.erb
<h1>New User</h1>

app/views/users/show.html.erb
<div class="user-show">
  <div class="user-boats">
    <h2>My Boats</h2>

    <% @boats.each do |boat| %>
    	<p><strong>Name:</strong></p>
         <p><%= boat.name %></p>
      <p><strong>Containers:</strong></p>
         <p><%= boat.containers %></p>
      <p><strong>Location:</strong></p>
         <p><%= boat.location %></p>
      <p><%= link_to "Show Boat", boat %></p>
      <hr>
    <% end %>
  </div>

  <div class="user-jobs">
    <h2>My Jobs</h2>
    <% @jobs.each do |job| %>
      <p><strong>Name:</strong></p>
        <p><%= job.name %></p>
      <p><strong>Description:</strong></p>
        <p><%= job.description %></p>
      <p><strong>Origin:</strong></p>
        <p><%= job.origin %></p>
      <p><strong>Destination:</strong></p>
        <p><%= job.destination %></p>
      <p><strong>Cost:</strong></p>
        <p><%= job.cost %></p>
      <p><strong>Containers:</strong></p>
        <p><%= job.containers %></p>
      <p><%= link_to 'Show Job', job %></p>
      <hr>
    <% end %>
  </div>

</div>